import 'dart:async';

import 'package:flutter/material.dart';
import 'package:sqflite/sqflite.dart';
import 'package:toolery/database/startdb.dart';
import 'package:toolery/models/tag.dart';

/// Defines the data-access contract for [Tag] persistence.
///
/// Concrete implementations (e.g. [SqliteTagRepository]) are injected into
/// [TagNotifier] so the notifier stays database-agnostic and testable.
abstract class TagRepository {
  /// Returns all tags in insertion order.
  Future<List<Tag>> allTags();

  /// Persists [tag] to the store. The stored id is generated by the database.
  Future<void> insertTag(Tag tag);

  /// Returns the tag with the given [id], or a sentinel "Null" tag if none exists.
  Future<Tag> getTag(int id);

  /// Overwrites the stored record that matches [tag.id] with new field values.
  Future<void> updateTag(Tag tag);

  /// Permanently removes the tag with [id] and any task/breathing join-table rows
  /// that reference it, preventing orphaned foreign-key records.
  Future<void> deleteTag(int id);

  /// Completes when the repository has finished initialising and is ready to use.
  Future<void> get ready;
}

class SqliteTagRepository implements TagRepository {
  late Database db;
  final String table = 'tag';
  final String joinTable = 'tasktag';
  final Completer<void> _ready = Completer<void>();

  SqliteTagRepository() {
    _initDB();
  }

  Future<void> _initDB() async {
    db = await getDatabase();
    // mark repository as ready
    if (!_ready.isCompleted) _ready.complete();
  }

  @override
  Future<void> get ready => _ready.future;

  Tag _fromMap(Map<String, Object?> m) => Tag.fromMap(m);

  Map<String, Object?> _toMap(Tag t) => t.toMap();

  @override
  Future<void> deleteTag(int id) async {
    await db.delete(table, where: 'id = ?', whereArgs: [id]);
    await db.delete(joinTable, where: 'tagID = ?', whereArgs: [id]);
  }

  @override
  Future<void> insertTag(Tag tag) async {
    Map<String, Object?> map = _toMap(tag);
    map.remove('id');
    await db.insert(table, map, conflictAlgorithm: ConflictAlgorithm.replace);
  }

  @override
  Future<List<Tag>> allTags() async {
    final rows = await db.query(table);
    return rows.map((r) => _fromMap(r)).toList();
  }

  @override
  Future<Tag> getTag(int id) async {
    final rows = await db.query(
      table,
      where: 'id = ?',
      whereArgs: [id],
      limit: 1,
    );
    if (rows.isEmpty) {
      return const Tag(id: -1, name: 'Null', color: Colors.red);
    }
    return _fromMap(rows.first);
  }

  @override
  Future<void> updateTag(Tag tag) async {
    final map = _toMap(tag);
    final id = map['id'];
    if (id == null) return;
    await db.update(table, map, where: 'id = ?', whereArgs: [id]);
  }
}
